export const STRINGS = {
  welcomePageTitle: "Your favorites horror movies at one click",
  welcomePageButton: "Let's go!",
  signInButton: "Sign in",
  signUpQuote: "It's my first time, I want to",
  signUpLink: "sign up",
  signUpButton: "Sign up",
  navbarMovies: "My movies",
  navbarExplore: "Explore",
  navbarLogout: "Log out",
  gridCardLink: " Click here for more info",
  gridCardDetailsReleaseDate: "Release date: ",
  gridCardDetailsOriginalLanguage: "Original Language: ",
  gridCardDetailsVote: "Vote: ",
  gridCardDetailsOverview: "Overview: ",
  gridCardDetailsPendingButton: "Add to pending",
  gridCardDetailsFavoriteButton: "Add to favorites",
  gridCardDetailsHomeButton: "Back to home",
  favoritesTitle: "Favorites",
  pendingTitle: "Pending",
  noMovies: " No movies yet :(",
  olderMovies: "Older movies",
  newestMovies: "Newest movies",
  footerName: "Belén JN",
  footerRights: "© 2022 All Rights reserved"
};
